### ISSUE TITLE
Congrats on the great work. Is there a script/notebook available for training?

### ISSUE THREAD

**Issue by frouhi** [bshall/urhythmic#1]
the demo is very impressive. I'm trying to train it on a custom source/target pair to get a better scene. I was wondering if there are scripts/notebooks to assist with that?

Thanks

**Comment by bshall** [comment]
Hi @frouhi, thanks for the feedback! I'm just tidying up the training scripts now. I should have them out in the next day or two. I'll let you know when they're out.

**Comment by bshall** [comment]
Hi @frouhi, I've released all the training scripts so you should be able to get everything working by following the readme. Let me know if you have any issues.

**Comment by frouhi** [comment]
Great. Thanks @bshall
