### ISSUE TITLE
train_segmenter.py not provided

### ISSUE THREAD

**Issue by hippotabek** [bshall/urhythmic#2]
Thank you very much for sharing your work!

I am trying to train the model on custom voice but I think u forgot to provide_segmenter.py file. Can I use one of the checkpoints instead? Or training is needed for a each individual speaker?

**Comment by bshall** [comment]
Hi @hippotabek, sorry I forgot to add that script. I've included it now but I would just recommend fitting the rhythm model and finetuning the vocoder if you want to adapt the model to a new speaker. The `Segmenter` is speaker independent so the pretrained checkpoint should be fine.
